domain: "hawkkiller.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://hawkkiller.github.io" # the base hostname & protocol for your site, e.g. http://example.com
title: "Michael Lazebny" # the name of your site, e.g. ACME Corp.

sass:
  implementation: sassc
  style: compact
  sass_dir: _sass
  line_comments: true
  sourcemap: always

permalink: pretty 