domain: "hawkkiller.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://hawkkiller.github.io/portfolio" # the base hostname & protocol for your site, e.g. http://example.com
title: "Michael Lazebny" # the name of your site, e.g. ACME Corp.

sass:
  implementation: sassc
  style: compact
  sass_dir: _sass
  line_comments: true
  sourcemap: always
