baseURL = 'https://hawkkiller.github.io'
languageCode = 'en-us'
title = 'portfolio'
[params]
  author = 'Michael Lazebny'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  identifier = 'home'
  weight = 1
[[menu.main]]
  name = 'About'
  url = '/about'
  identifier = 'about'
  weight = 2
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  identifier = 'contact'
  weight = 3
