baseURL = 'https://themisha.dev'
languageCode = 'en-us'
title = 'portfolio'
staticDir = ['static']
[Params]
  author = 'Michael Lazebny'
  Github = 'https://github.com/hawkkiller/'
  Linkedin = 'https://www.linkedin.com/in/michael-lazebnyi'
  Twitter = 'https://twitter.com/michaellazebnyi'
  Gmail = 'mailto:miskadl09@gmail.com'
    
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  identifier = 'home'
  weight = 1
[[menu.main]]
  name = 'About'
  url = '/about'
  identifier = 'about'
  weight = 2
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  identifier = 'contact'
  weight = 3
