baseURL = 'https://themisha.dev'
defaultContentLanguage = 'en'
languageCode = 'en-us'
[params]
  Github = 'https://github.com/hawkkiller/'
  Linkedin = 'https://www.linkedin.com/in/michael-lazebnyi'
  Twitter = 'https://twitter.com/michaellazebnyi'
  Gmail = 'mailto:miskadl09@gmail.com'

[languages]
  [languages.en]
    title = 'Michael Lazebny'
    description = 'Michael Lazebny personal website'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1
    [languages.en.params]
      author = 'Michael Lazebny'
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Home'
        url = '/'
        identifier = 'home'
        weight = 1
      [[languages.en.menu.main]]
        name = 'About'
        url = '/about'
        identifier = 'about'
        weight = 2
      [[languages.en.menu.main]]
        name = 'Contact'
        url = '/contact'
        identifier = 'contact'
        weight = 3